---
title: "Actuarial"
author: "Jos?? Antonio Gonz??lez Acosta"
date: "30 de mayo de 2019"
output: html_document
---





```{r}
set.seed(1)
install.packages("readxl")
install.packages("actuar")
install.packages("gPdtest")
install.packages("fitdistrplus")


```

```{r}
library("readxl")
library("actuar")
library("gPdtest")
library("fitdistrplus")
```




```{r}
#Lectura de los datos
getwd()
setwd("C:/Users/jcasarest/Documents/Actuarial")

Danish<-read_xlsx("Danish.xlsx", 1)
Prueba<-read.csv("Prueba.csv", 1)
data <- as.data.frame(Danish)
colnames(data)[1] <- "Date"
sub <- data[order(data$Date),]
year <- as.integer(substring(as.character(sub$Date),1,4))
sub$Date <- year
##


#Gr??fica frecuencia de siniestros por a??o
FreqY <- c(1980:1988)
for (i in 1:length(FreqY)) {
  FreqY[i] <- length(sub[sub$Date == FreqY[i],6])
}
View(FreqY)
seq1 <- 1980:1988
plot(seq1,FreqY,type = "l",main = "Frecuencia de siniestros 1980-1988", xlab = "Año", ylab = "Valor de las perdidas")
##

#Graficas severidades por cada tipo de Siniestro

idx <- sample(1:NROW(Danish), 20)
barplot(Danish$Edificio[idx], col = "grey25", ylim = c(0, max(Danish$total[idx])), main = "Some claims of danish data set") 
barplot(Danish$Contenido[idx], add = TRUE, col = "grey50", axes = FALSE) 
barplot(Danish$Ventas[idx], add = TRUE, col = "darkblue", axes = FALSE) 

legend("topleft", legend = c("Building", "Content", "Profits"), fill = c("grey25", "grey50", "darkblue"))



#frecuencia total por FREQY
P<-fitdist(FreqY,"pois")
N<-fitdist(data=FreqY,distr="nbinom",method="mle")
r.fit = N$estimate['size']
p.fit = r.fit/ (N$estimate['mu'] + r.fit)
p<-p.fit


summary(P)


cdfcomp(list(P,N),legendtext = c("pois","nbinom"))
qqcomp(list(P,N),legendtext = c("pois","nbinom"))


#Frecuencia total por arrival
Poi<-fitdist(sub$Arrival,"pois")
N<-fitdist(sub$Arrival,"nbinom")


plot(Poi)
plot(N)
cdfcomp(list(Poi,N),legendtext = c("pois","nbinom"))
qqcomp(list(Poi,N),legendtext = c("pois","nbinom"))


#Severidad total
G<-fitdist(sub$total,"gamma",lower=c(0,0))
P<-fitdist(sub$total,"pareto")
W <- fitdist(sub$total, "weibull")
LN <- fitdist(sub$total, "lnorm")
E<-fitdist(sub$total,"exp")

plot(W)
plot(G)
plot(LN)
plot(E)
plot(P)
View(P)

summary(P)

par(mfrow=c(1,1))
qqcomp(list(G,W,LN,E,P),legendtext = c("gamma","weibull","lnrom","exp","pareto"))
cdfcomp(list(G,W,LN,E,P),legendtext = c("gamma","weibull","lnrom","exp","pareto"))



#Primero: para la frecuencia seleccionamos la binomial negativa con parametros:

#Segundo: para la severidad elegimos una pareto


#Para la distribuci?n de S realizamos una Simulaci?n Estocastica
m<-1
M<-1000
S_sim <- matrix(NA,ncol=1,nrow=M)
N_sim <- matrix(NA,ncol=1,nrow=M)

for(m in 1:M){

  n_sim <- rnbinom(1,57.97,p)
  x_sim <- rpareto(n_sim,6,15)
  S_sim[m] <- sum(x_sim)
}
summary(S_sim)

#Para los Datos de Prueba
data <- as.data.frame(Prueba)
colnames(data)[1] <- "Date"
sub <- data[order(data$Date),]
yearprueba <- as.integer(substring(as.character(sub$Date),7,10))
sub$Date <- yearprueba


totalprueba <- c(1989:1990)
for (i in 1:length(totalprueba)) {
  totalprueba[i] <- sum(sub[sub$Date == totalprueba[i],5])
 }

#Para las Primas

#prima base tomada como el promedio de la distribuci?n de S
Ps=mean(S_sim)
View(Ps)
View(S_sim)
View(summary(S_sim))


#Prima Tvar alfa=0.999
alfa<-0.999
Var<-quantile(S_sim,alfa)
Pvar=Var
View(Pvar)
#Prima utilidad cero
#definimos la funcion utilidad como u(x)=ln(x)
U_vector <- matrix(NA,ncol=1,nrow=M)
W<-1000
sigma<-.5
for(m in 1:M){
  U_vector[m]<-((m^sigma-1)/(1-sigma)) # la parte de utilidad cero la resolvimos en excel(está adjunto)
  
}

seq2<-1:1000
plot(U_vector)
#log(S_sim[m])
#(m^sigma-1)/(1-sigma)




####################################################################################################




#9
deducible<-.1
coaseguro<-.95
lim_cobertura_total<-25
new_total <- numeric(length(sub$total))

for (i in 1:(length(sub$total))) {
  if (sub$total[i]<lim_cobertura_total) {
    new_total[i]<-coaseguro*(sub$total[i])*(1-deducible)
  }
  if (sub$total[i]>=lim_cobertura_total) {
    new_total[i]<-coaseguro*(lim_cobertura_total-deducible*sub$total[i])
  }
}
View(new_total)


G_2<-fitdist(new_total,"gamma", lower=c(0,0))
P_2<-fitdist(new_total,"pareto")
W_2 <- fitdist(new_total, "weibull")
LN_2 <- fitdist(new_total, "lnorm")
E_2<-fitdist(new_total,"exp")

plot(W_2)
plot(G_2)
plot(LN_2)
plot(E_2)
plot(P_2)
View(P_2)



par(mfrow=c(1,1))
qqcomp(list(G_2,W_2,LN_2,E_2,P_2),legendtext = c("gamma","weibull","lnrom","exp","pareto"))
cdfcomp(list(G_2,W_2,LN_2,E_2,P_2),legendtext = c("gamma","weibull","lnrom","exp","pareto"))


#esperanza de St

#Primero: para la frecuencia seleccionamos la binomial negativa con parametros:

#Segundo: para la severidad elegimos una pareto


#Para la distribuci?n de S realizamos una Simulaci?n Estocastica
m_2<-1
M_2<-1000
S_sim_2 <- matrix(NA,ncol=1,nrow=M)
N_sim_2 <- matrix(NA,ncol=1,nrow=M)

for(m_2 in 1:M_2){

  n_sim_2 <- rnbinom(1,57.97,p)
  x_sim_2 <- rpareto(n_sim,9,20)
  S_sim_2[m_2] <- sum(x_sim_2)
}

summary(S_sim_2)

#Para los Datos de Prueba
data <- as.data.frame(Prueba)
colnames(data)[1] <- "Date"
sub <- data[order(data$Date),]
yearprueba <- as.integer(substring(as.character(sub$Date),7,10))
sub$Date <- yearprueba


totalprueba <- c(1989:1990)
for (i in 1:length(totalprueba)) {
  totalprueba[i] <- sum(sub[sub$Date == totalprueba[i],5])
 }

#Para las Primas

#prima base tomada como el promedio de la distribuci?n de S
Ps_2=mean(S_sim_2)
View(Ps_2)
View(S_sim_2)


#Prima Tvar alfa=0.999
alfa_2<-0.999
Var_2<-quantile(S_sim_2,alfa_2)
Pvar_2=Var_2
View(Pvar_2)
#Prima utilidad cero
#definimos la funcion utilidad como u(x)=ln(x)
U_vector_2 <- matrix(NA,ncol=1,nrow=M)
W_2<-1000
sigma_2<-.5
for(m_2 in 1:M_2){
  U_vector_2[m_2]<-((m_2^sigma_2-1)/(1-sigma_2)) # la parte de utilidad cero la resolvimos en excel(está adjunto)
  
}

seq2_2<-1:1000
plot(U_vector_2)
#log(S_sim[m])
#(m^sigma-1)/(1-sigma)

summary(P)
summary(P_2)
```

