---
title: "Tarea 02 - Calculo Actuarial III"
author: "Luis Vázquez"
date: "17/2/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Modifiquen la funcion **Poisson.Plot()** para crear la funcion **BinNeg.Plot()** para  generar los resultados analogos

Ver codigo para ver como se genera la grafica.

```{r poisson_binNeg_plot, include=FALSE}
BinNegModif.plot <- function(n, r, p, a=NA,b=NA,calcProb=(!is.na(a) | !is.na(b)),quantile=NA,calcQuant=!is.na(quantile)){
  # BinNeg
  media <- r*(1-p)/p
  sd = sqrt(r*(1-p)/p^2)
  low = max(0, round(media - 3 * sd))
  high = round(media + 5 * sd)
  values = low:high
  probs = dnbinom(x = values, size = r, prob = p)
  plot(c(low,high), c(0,max(probs)), type = "n", 
       xlab = "Numero de casos",
       ylab = "Masas de probabilidad",
       main = "Binomial Negativa")
  lines(values, probs, type = "h", col = 2)
  abline(h=0,col=3)
  if(calcProb) {
    if(is.na(a)){ a = 0 }
    if(is.na(b)){
      a = round(a)
      prob = 1-pnbinom(q= a-1,size = r, prob = p)
      title(paste("P(",a," <= Y ) = ",round(prob,6),sep=""),line=0,col.main=4)
      u = seq(max(c(a,low)),high,by=1)
    }
    else {
      if(a > b) {d = a; a = b; b = d;}
      a = round(a); b = round(b)
      prob = pnbinom(q= b,size = r, prob = p) - pnbinom(q= a-1,size = r,prob = p)
      title(paste("P(",a," <= N <= ",b,") = ",round(prob,6),sep=""),line=0,col.main=4)
      u = seq(max(c(a,low)),min(c(b,high)),by=1)
    }
    v = dnbinom(x= u,size = r, prob = p)
    lines(u,v,type="h",col=4)
  }
  else if(calcQuant==T) {
    if(quantile < 0 || quantile > 1)
      stop("El cuantil debe estar entre 0 y 1")
    x = qnbinom(p = quantile,size= r,prob = p)
    title(paste("",quantile," quantile = ",x,sep=""),line=0,col.main=4)
    u = 0:x
    v = dnbinom(x = u,size = r, prob = p)
    lines(u,v,type="h",col=4)
  }
  return(invisible())
}
```

```{r}

BinNegModif.plot(300,40,0.7)

```


 
